import { Bone } from '../types/rigging';

export function generateFBXFile(bones: Bone[], armatureName = "RigMasterArmature"): string {
  const fbxId = (idStr: string) => {
    let hash = 0;
    for (let i = 0; i < idStr.length; i++) {
      hash = (hash << 5) - hash + idStr.charCodeAt(i);
      hash |= 0;
    }
    return Math.abs(hash * 1000) + 100000;
  };

  const lines: string[] = [];
  lines.push(`; FBX 7.4.0 project file generated by RigMaster 3D Studio`);
  lines.push(`FBXHeaderExtension:  {`);
  lines.push(`\tFBXHeaderVersion: 1003`);
  lines.push(`\tFBXVersion: 7400`);
  lines.push(`\tCreator: "RigMaster 3D Studio - Offline Rigging Practice App"`);
  lines.push(`}`);
  lines.push(`GlobalSettings:  {`);
  lines.push(`\tVersion: 1000`);
  lines.push(`\tProperties70:  {`);
  lines.push(`\t\tP: "UpAxis", "int", "Integer", "",1`);
  lines.push(`\t\tP: "UpAxisSign", "int", "Integer", "",1`);
  lines.push(`\t\tP: "FrontAxis", "int", "Integer", "",2`);
  lines.push(`\t\tP: "FrontAxisSign", "int", "Integer", "",1`);
  lines.push(`\t\tP: "CoordAxis", "int", "Integer", "",0`);
  lines.push(`\t\tP: "CoordAxisSign", "int", "Integer", "",1`);
  lines.push(`\t\tP: "OriginalUpAxis", "int", "Integer", "",1`);
  lines.push(`\t\tP: "OriginalUpAxisSign", "int", "Integer", "",1`);
  lines.push(`\t\tP: "UnitScaleFactor", "double", "Number", "",1.0`);
  lines.push(`\t}`);
  lines.push(`}`);
  lines.push(`Objects:  {`);

  const armatureId = fbxId(armatureName);
  lines.push(`\tModel: ${armatureId}, "Model::${armatureName}", "Null" {`);
  lines.push(`\t\tVersion: 232`);
  lines.push(`\t\tProperties70:  {`);
  lines.push(`\t\t\tP: "InheritType", "enum", "", "",1`);
  lines.push(`\t\t}`);
  lines.push(`\t}`);

  bones.forEach((bone) => {
    const boneId = fbxId(bone.id);
    const hX = (bone.head.x - 400) / 10;
    const hY = (1000 - bone.head.y - 500) / 10;
    const hZ = (bone.head.z || 0) / 10;

    lines.push(`\tModel: ${boneId}, "Model::${bone.name}", "LimbNode" {`);
    lines.push(`\t\tVersion: 232`);
    lines.push(`\t\tProperties70:  {`);
    lines.push(`\t\t\tP: "LimbLength", "double", "Number", "", ${Math.hypot(bone.tail.x - bone.head.x, bone.tail.y - bone.head.y) / 10}`);
    lines.push(`\t\t\tP: "Lcl Translation", "Lcl Translation", "", "A",${hX.toFixed(4)},${hY.toFixed(4)},${hZ.toFixed(4)}`);
    lines.push(`\t\t\tP: "Lcl Rotation", "Lcl Rotation", "", "A",0,0,${bone.roll}`);
    lines.push(`\t\t}`);
    lines.push(`\t}`);
  });

  lines.push(`}`);

  lines.push(`Connections:  {`);
  // Connect root armature to scene
  lines.push(`\tC: "OO",${armatureId},0`);

  bones.forEach((bone) => {
    const boneId = fbxId(bone.id);
    if (bone.parentId) {
      const parentBone = bones.find(b => b.id === bone.parentId);
      if (parentBone) {
        lines.push(`\tC: "OO",${boneId},${fbxId(parentBone.id)}`);
      } else {
        lines.push(`\tC: "OO",${boneId},${armatureId}`);
      }
    } else {
      lines.push(`\tC: "OO",${boneId},${armatureId}`);
    }
  });

  lines.push(`}`);

  return lines.join('\n');
}
